name: ebook
on:
  workflow_dispatch:
jobs:
  ebook-job:
    runs-on: ubuntu-latest
    container:
      image: lscr.io/linuxserver/calibre
    steps:
      - uses: actions/checkout@v4
      - name:  create-ebook
        run: |
             sudo apt update && sudo apt install -y  python3-mechanicalsoup
             python3 download.py
             ebook-convert aa/index.html   aaa.mobi
